name: docker action build
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run ontainer action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: "test"
          
      - name: Output time set in the container
        run: echo "Hello ${{ steps.hello-action.outputs.greeting }}"
